---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-config
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "synology-iscsi-storage"
  resources:
    requests:
      storage: 1Gi
